name: release

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
    - name: checkout
      uses: actions/checkout@v4
    
    - name: initialize
      run: |
        sudo apt-get -y update
        sudo -E apt-get -y install build-essential python3 iasl lzop unifont autopoint bison flex gettext gcc-mingw-w64
    
    - name: bootstrap
      run: ./bootstrap

    - name: build all targets
      run: |
        targets=(
          "x86_64:efi"
          "i386:efi"
          "i386:pc"
          "i386:multiboot"
        )
        
        for target in "${targets[@]}"; do
          IFS=':' read -r arch platform <<< "$target"
          echo "Building $arch-$platform..."
          ./configure --prefix=/ --target=$arch --with-platform=$platform
          make
          make install DESTDIR=$PWD/PKG
          make clean
        done

    - name: makepkg
      run: ./makepkg.sh
    
    - name: upload
      uses: marvinpinto/action-automatic-releases@latest
      with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "latest"
          prerelease: false
          title: "Development Build"
          files: grub2-latest.tar.gzcrets.GITHUB_TOKEN }}"
          automatic_release_tag: "latest"
          prerelease: false
          title: "Development Build"
          files: grub2-latest.tar.gz
